apiVersion: v1
kind: Pod
metadata:
  name: hpl-pod1
  labels:
    app: hpl
spec:
  tolerations:
  nodeName: master  # Explicitly target master by name, not by selector
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: hpl
    image: ubuntu:20.04
    command: ["sleep", "infinity"]
    securityContext:
      privileged: true
      capabilities:
        add: ["NET_RAW"]
    resources:
      requests:
        memory: "1024Mi"
        cpu: "1"
      limits:
        memory: "1024Mi"
        cpu: "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: hpl-pod2
  labels:
    app: hpl
spec:
  # Specify the first worker node
  nodeName: node01
  containers:
  - name: hpl
    image: ubuntu:20.04
    command: ["sleep", "infinity"]
    securityContext:
      privileged: true
      capabilities:
        add: ["NET_RAW"]
    resources:
      requests:
        memory: "1024Mi"
        cpu: "1"
      limits:
        memory: "1024Mi"
        cpu: "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: hpl-pod3
  labels:
    app: hpl
spec:
  # Specify the second worker node
  nodeName: node02
  containers:
  - name: hpl
    image: ubuntu:20.04
    command: ["sleep", "infinity"]
    securityContext:
      privileged: true
      capabilities:
        add: ["NET_RAW"]
    resources:
      requests:
        memory: "1024Mi"
        cpu: "1"
      limits:
        memory: "1024Mi"
        cpu: "1"