version: '3.8'

services:
  app1:
    image: ubuntu
    command: sleep infinity
    networks:
      - internal_net
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1GB"
    cpuset: "0"

  app2:
    image: ubuntu
    command: sleep infinity
    networks:
      - internal_net
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1GB"
    cpuset: "1"

  app3:
    image: ubuntu
    command: sleep infinity
    networks:
      - internal_net
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1GB"
    cpuset: "2"

networks:
  internal_net:
    driver: bridge

